name: Java CI with Maven and Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      working-directory: bookstore/backend
      run: mvn clean install

    - name: Upload JAR/WAR artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bookstore-artifacts
        path: bookstore/backend/target

    - name: Build Docker image
      working-directory: bookstore/backend
      run: docker build -t ray6811/bookstore-backend:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push ray6811/bookstore-backend:latest
